version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  build-and-test:
    jobs:
      - build:
          steps:
            - checkout

            # Install pnpm
            - run: npm install -g pnpm
            - run: pnpm install

            - run: pnpm build
