version: 2.1

orbs:
  node: circleci/node@5.1.0
  gh: circleci/github-cli@2.2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-deps-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: app-deps-{{ checksum "package.json" }}
      - run: yarn build
      - run: echo 'https://nhanlt6.github.io/modernisation-challenge-vue3/' > dist/CNAME
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: git config --global user.name "Nhan Le"
      - run: git config --global user.email "letrongnhan1306@gmail.com"
      - run: git clone https://github.com/NhanLT6/modernisation-challenge-vue3.git
      - run: cd modernisation-challenge-vue3 && git checkout -b gh-pages-1
      - run: cp -r ./dist/* . # Copy dist folder from build step to root
      - run: git add .
      - run: git commit -m "Deploy to GitHub Pages"
      - run: git push origin gh-pages-1

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circleci-project-setup
