version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm install -g pnpm # Install pnpm
      - run: pnpm install
      - run: pnpm build

workflows:
  build-and-test:
    jobs:
      - build
