version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-deps-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: app-deps-{{ checksum "package.json" }}
      - run: yarn build
      - run: echo 'https://nhanlt6.github.io/modernisation-challenge-vue3/' > dist/CNAME
      - run: cp -r dist public

  deploy:
    executor: node/default
    steps:
      - checkout
      - run: npx gh-pages --dist public --add --message "Deploy to GitHub Pages"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
